### ISSUE TITLE
Method Not Allowed (CORS)

### ISSUE THREAD

**Issue by CraigglesO** [mrbbot/slshx#10]
Uploading this template to cloudflare and accessing the site I get `Method Not Allowed`. 
I am convinced it is a cors issue, but not sure how to make changes since slshx handles everything.

**Comment by CraigglesO** [comment]
Looking at the source code, it returns Method Not Allowed for any requests that are not POST. I figured you could access the "Add to server" page after you setup the worker but this is not the case. You need to use dev mode + tunnel/localhost to add the application BEFORE you try to use it online.

**Comment by Lencof** [comment]
hmm.... this project worked?

**Comment by CraigglesO** [comment]
Yeah, I should close this issue. Using the tutorials in the README got me to a usable API online.
